apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-helm-repositories
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/helm-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra-helm-repositories
  path: ./infra/external-secrets/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-creds
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: external-secrets-operator
  path: ./infra/external-secrets/creds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-store
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: external-secrets-creds
  path: ./infra/external-secrets/store
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: external-secrets-store
  path: ./infra/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: homelab-issuer-vars
      - kind: Secret
        name: azuredns-config

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-arc
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/actions-runner-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-cnpg
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/cnpg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/metallb/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metallb-resources
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: core-metallb
  path: ./infra/metallb/resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-metrics-server
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-opentelemetry-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/opentelemetry-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-redis-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/redis-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-reloader
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-strimzi
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/strimzi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-tailscale-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
  path: ./infra/tailscale-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-fallback
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: core-ingress-nginx
  path: ./apps/fallbacksite
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
