apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 10m
  chart:
    spec:
      chart: harbor
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    expose:
      type: ingress
      tls:
        enabled: true
      ingress:
        className: tailscale
      hosts:
        core: harbor
    notary:
      enabled: false