apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
spec:
  provider:
    azurekv:
      tenantId: "41dff8ea-5523-4210-b3ef-29349f3fbe14"
      vaultUrl: "https://kubesoar-homelab-67029.vault.azure.net/"
      environmentType: "AzurePublicCloud"
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: akv-eso-creds
          namespace: external-secrets
          key: clientId
        clientSecret:
          name: akv-eso-creds
          namespace: external-secrets
          key: clientSecret