apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape
  namespace: kubescape
spec:
  interval: 10m
  chart:
    spec:
      chart: kubescape-operator
      version: "1.29.10"
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3