apiVersion: v1
kind: Namespace
metadata:
  name: nginx-funnel
  labels:
    app.kubernetes.io/name: nginx-funnel

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-funnel-quota
  namespace: nginx-funnel
spec:
  hard:
    pods: "10"
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "2Gi"
    configmaps: "20"
    services: "10"
    secrets: "20"


---

apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: nginx-funnel
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-pages
  namespace: nginx-funnel
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Home</title></head>
      <body style="font-family: sans-serif">
        <h1>Welcome to NGINX</h1>
        <p>Served from a Kubernetes ConfigMap folder.</p>
        <ul>
          <li><a href="/about.html">About</a></li>
          <li><a href="/status.html">Status</a></li>
        </ul>
      </body>
    </html>
  about.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>About</title></head>
      <body style="font-family: sans-serif">
        <h1>About This Site</h1>
        <p>These pages live inside a ConfigMap that is mounted as a directory.</p>
        <p><a href="/">Home</a></p>
      </body>
    </html>
  status.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Status</title></head>
      <body style="font-family: sans-serif">
        <h1>Status</h1>
        <p>✅ All systems good.</p>
        <p><a href="/">Home</a></p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-funnel
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: site
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: site
          configMap:
            name: nginx-pages
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-funnel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: nginx-funnel
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
