apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "*"
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      ingressClassResource:
        default: true
  valuesFrom:
    - kind: Secret
      name: ingress-nginx-network
      valuesKey: ingress-lb-ip
      targetPath: controller.service.loadBalancerIP