kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "datadog"
spec:
  global:
    site: "us5.datadoghq.com"
    clusterName: "homelab-cluster"
    tags:
      - "env:homelab"
    credentials:
      apiSecret:
        secretName: "datadog-credentials"
        keyName: "api-key"
      appSecret:
        secretName: "datadog-credentials"
        keyName: "app-key"

  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: "otel-grpc"
        - containerPort: 4318
          hostPort: 4318
          name: "otel-http"

