# infra/external-secrets/resources/clustersecretstore-azure-kv.yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
spec:
  provider:
    azurekv:
      tenantId: ${AZURE_TENANT_ID}
      vaultUrl: ${AZURE_VAULT_URL}
      environmentType: ${AZURE_ENVIRONMENT}
      clientId: ${AZURE_CLIENT_ID}
      authSecretRef:
        clientSecret:
          name: akv-eso-creds
          namespace: external-secrets
          key: clientSecret
