apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
spec:
  provider:
    azurekv:
      vaultUrl: https://homelab-kv.vault.azure.net
      authType: ServicePrincipal
      tenantId:
        valueFrom:
          secretKeyRef:
            name: akv-eso-creds
            namespace: external-secrets
            key: tenantId
      clientId:
        valueFrom:
          secretKeyRef:
            name: akv-eso-creds
            namespace: external-secrets
            key: clientId
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: akv-eso-creds
            namespace: external-secrets
            key: clientSecret
