apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: operator-oauth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: clientId
      remoteRef:
        key: tailscale-client-id
    - secretKey: clientSecret
      remoteRef:
        key: tailscale-client-secret
