apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: controller-manager
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: github_token
      remoteRef:
        key: github-token
