apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-issuer-vars
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: homelab-issuer-vars
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ACME_EMAIL
      remoteRef:
        key: acme-email
    - secretKey: AZURE_DNS_ZONE
      remoteRef:
        key: azure-dns-zone
    - secretKey: AZURE_SUBSCRIPTION_ID
      remoteRef:
        key: azure-subscription-id
    - secretKey: AZURE_DNS_RG
      remoteRef:
        key: azure-dns-rg
    - secretKey: AZURE_TENANT_ID
      remoteRef:
        key: azure-tenant-id
    - secretKey: AZURE_CLIENT_ID
      remoteRef:
        key: azure-client-id
    - secretKey: AZURE_ENVIRONMENT
      remoteRef:
        key: azure-environment
    - secretKey: INGRESS_LB_IP
      remoteRef:
        key: ingress-lb-ip
    - secretKey: ROOT_DOMAIN
      remoteRef:
        key: root-domain
    - secretKey: WILDCARD_DOMAIN
      remoteRef:
        key: wildcard-domain
    - secretKey: TLS_SECRET_NAME
      remoteRef:
        key: tls-secret-name
    - secretKey: AKV_NAME
      remoteRef:
        key: kv-name
