apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azuredns-config-flux-system
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: azuredns-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: azuredns-client-id
    - secretKey: client_secret
      remoteRef:
        key: azuredns-client-secret
    - secretKey: subscription_id
      remoteRef:
        key: azuredns-subscription-id
    - secretKey: tenant_id
      remoteRef:
        key: azuredns-tenant-id


---


apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azuredns-config-cert-manager
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: azuredns-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: azuredns-client-id
    - secretKey: client_secret
      remoteRef:
        key: azuredns-client-secret
    - secretKey: subscription_id
      remoteRef:
        key: azuredns-subscription-id
    - secretKey: tenant_id
      remoteRef:
        key: azuredns-tenant-id