apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-credentials
  namespace: datadog
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: datadog-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: api-key
      remoteRef:
        key: datadog-api-key
    - secretKey: app-key
      remoteRef:
        key: datadog-app-key
