apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog-operator
  namespace: datadog
spec:
  interval: 10m
  chart:
    spec:
      chart: datadog-operator
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
      version: "2.15.0-dev.2"
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    clusterName: "homelab-cluster"
    apiKeyExistingSecret: "datadog-credentials"
    appKeyExistingSecret: "datadog-credentials"
    site: "us5.datadoghq.com"
    datadogAgent:
      enabled: true
    datadogAgentInternal:
      enabled: false
    datadogDashboard:
      enabled: false
    datadogGenericResource:
      enabled: false
    datadogMonitor:
      enabled: false
    datadogSLO:
      enabled: false
    remoteConfiguration:
      enabled: true
    
    watchNamespaces:
      - "*"

    datadogCRDs:
      crds:
        datadogAgents: true
        datadogMetrics: true
        datadogPodAutoscalers: true
        datadogMonitors: true
        datadogSLOs: true
        datadogDashboards: true
        datadogGenericResources: true
        datadogAgentProfiles: true

    clusterRole:
      allowReadAllResources: true
      allowCreatePodsExec: true
